# Generated by Django 4.2.11 on 2024-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=400)),
                ('note_publisher', models.CharField(max_length=20)),
                ('note_rating', models.IntegerField(default=1, verbose_name='rating')),
                ('note_pub_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
    ]
