# Generated by Django 4.2.11 on 2024-04-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_rating',
        ),
        migrations.AddField(
            model_name='note',
            name='business_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
